#pragma once

// #1237: what each face's characters measure, so the badge's layout can place text it
// doesn't draw itself. Org_01 is proportional (2-6 px), so counting characters stopped
// being enough.
//
// GENERATED by tools/gen_badge_fonts.py from Adafruit GFX Library 1.12.6 -- the
// same headers the badge build compiles. Don't edit by hand; re-run the generator.
//
// Pure: no Arduino and no mesh.

#include <stddef.h>
#include <stdint.h>

namespace badgeui {

constexpr uint8_t kFaceFirst = 0x20;   // the faces cover 0x20..0x7e
constexpr uint8_t kFaceLast = 0x7e;

static const uint8_t kBodyAdvance[] = {
    6, 2, 4, 6, 6, 6, 6, 2, 3, 3, 4, 4, 2, 5, 2, 6,
    6, 2, 6, 6, 6, 6, 6, 6, 6, 6, 2, 2, 4, 5, 4, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 6, 3, 4, 6,
    2, 5, 5, 5, 5, 5, 4, 5, 5, 2, 3, 5, 2, 6, 5, 5,
    5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 4, 2, 4, 6,
};

static const uint8_t kMetaAdvance[] = {
    2, 2, 4, 4, 4, 4, 4, 2, 3, 3, 4, 4, 3, 4, 2, 4,
    4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 2, 3, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    3, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4,
};

// A text face: how wide its characters are, how tall its rows sit, and the id the
// display driver takes to select it.
struct Face {
  const uint8_t* advance;   // per character from kFaceFirst; null for a fixed 6 px face
  uint8_t missing;          // for anything outside the range, and for a fixed face
  uint8_t row_px;           // the pitch rows sit on
  uint8_t id;               // DisplayDriver::setFace
};

// The display's own 6 x 8 font: every character 6 px, rows 8 px.
inline const Face& fixedFace() {
  static const Face f = {nullptr, 6, 8, 0};
  return f;
}

// Org_01: the badge's body text. Rows sit 7 px apart, so a screen holds 9.
inline const Face& bodyFace() {
  static const Face f = {kBodyAdvance, 6, 7, 1};
  return f;
}

// TomThumb: status lines, a message's detail line and footers. A 4 x 6 grid, 32 wide.
inline const Face& metaFace() {
  static const Face f = {kMetaAdvance, 4, 6, 2};
  return f;
}

inline int charPx(const Face& f, char c) {
  const uint8_t u = (uint8_t)c;
  if (f.advance == nullptr || u < kFaceFirst || u > kFaceLast) return f.missing;
  return f.advance[u - kFaceFirst];
}

inline int textPx(const Face& f, const char* s) {
  int px = 0;
  for (; *s != 0; s++) px += charPx(f, *s);
  return px;
}

// How many characters of `s` fit in `px`, never splitting past what fits.
inline int fitPx(const Face& f, const char* s, int px) {
  int used = 0, n = 0;
  for (; s[n] != 0; n++) {
    const int w = charPx(f, s[n]);
    if (used + w > px) break;
    used += w;
  }
  return n;
}

}  // namespace badgeui
