#pragma once

// #740 -- raw-UART0 boot beacon.
//
// WHY THIS EXISTS
// ---------------
// Three stages of the ESP32-S3 boot are invisible to every instrument this
// project had (see #702):
//
//   1. the second-stage bootloader is built CONFIG_BOOTLOADER_LOG_LEVEL_NONE,
//      so it prints nothing on success OR failure;
//   2. the prebuilt arduino-esp32 libraries are compiled
//      CONFIG_LOG_MAXIMUM_LEVEL=1, so every IDF INFO/DEBUG line in PSRAM/cache/
//      heap init is compiled out and cannot be re-enabled at runtime;
//   3. MeshLog and the CrashLog ring go to USB-CDC, which on a native-USB S3 is
//      generated by the chip itself -- it dies with the chip, so it can never
//      witness a boot that failed.
//
// This beacon writes single bytes straight into the UART0 TX FIFO register. It
// needs no driver, no FreeRTOS, no Arduino core and no logging framework, so it
// is usable from the very first executable instruction of the application --
// specifically from a constructor(101), which runs ahead of every other C++
// static constructor in the image.
//
// The single marker APP:CTOR is the load-bearing one: if it appears after an
// RST, the bootloader and IDF startup both completed and the fault is in our
// ctors/setup(); if it does not, the fault is at or before the bootloader's
// jump to the app and no application-level fix can ever address it.
//
// SAFETY: the FIFO-full spin reads UART_STATUS. If UART0 is unclocked the count
// reads 0, so the loop cannot spin forever -- a dead UART degrades to silent
// writes, never to a wedged boot (SAFELANE 11.8).
//
// Enable with -D OFFBAND_BOOT_BEACON. Compiles to nothing otherwise, so it is
// safe to leave the call sites in shipping code.

#if defined(OFFBAND_BOOT_BEACON) && !defined(ESP32)
// Gemini review (#740): a silent no-op is the wrong failure mode for a
// diagnostic. Asking for the beacon on a platform that cannot provide it must
// fail loudly at compile time, not leave someone debugging their instrument
// while it quietly does nothing. nRF52/RP2040 need their own implementation --
// see tools/diag/rc32-boot-740/README.md.
#error "OFFBAND_BOOT_BEACON is ESP32-only (raw UART0 FIFO writes). Remove the flag or add a port for this platform."
#endif

#if defined(OFFBAND_BOOT_BEACON) && defined(ESP32)

#include <stdint.h>
#include "soc/soc.h"        // READ_PERI_REG / WRITE_PERI_REG
#include "soc/uart_reg.h"   // UART_FIFO_REG / UART_STATUS_REG / UART_TXFIFO_CNT_*

#ifndef OFFBAND_BEACON_UART
  // UART0. On the RC32 this is GPIO43 (U0TXD) = header pin 12, the wire the
  // external sniffer is clipped to. Deliberately NOT USB-Serial-JTAG.
  #define OFFBAND_BEACON_UART 0
#endif

// ESP32-S3 UART TX FIFO is 128 bytes deep. Leave headroom rather than filling
// it exactly; this is a diagnostic, not a throughput path.
#ifndef OFFBAND_BEACON_FIFO_HIGHWATER
  #define OFFBAND_BEACON_FIFO_HIGHWATER 100
#endif

// BOUNDED spin. The first version of this looped unconditionally on the
// assumption that an unclocked UART reads TXFIFO_CNT == 0. That assumption was
// never verified, and it is the wrong way round to bet: a gated APB peripheral
// commonly reads all-ones, in which case (0xFFFFFFFF >> 16) & 0x3FF = 1023,
// the condition is permanently true, and the beacon HANGS THE BOARD it is
// supposed to be observing.
//
// SAFELANE 11.8 -- isolate every dangerous action so it cannot wedge the
// device. A diagnostic that can hang its own target is not a diagnostic. The
// bound is generous (a full 128-byte FIFO drains in ~11 ms at 115200, and each
// iteration is a few cycles at 240 MHz) so it never truncates real output, but
// it is finite, so worst case we lose bytes instead of the board.
static inline void offband_beacon_putc(char c) {
  uint32_t guard = 2000000;
  while (guard--) {
    uint32_t cnt = (READ_PERI_REG(UART_STATUS_REG(OFFBAND_BEACON_UART))
                    >> UART_TXFIFO_CNT_S) & UART_TXFIFO_CNT_V;
    if (cnt <= OFFBAND_BEACON_FIFO_HIGHWATER) break;
  }
  WRITE_PERI_REG(UART_FIFO_REG(OFFBAND_BEACON_UART), (uint32_t)(uint8_t)c);
}

static inline void offband_beacon_puts(const char* s) {
  if (!s) return;
  while (*s) offband_beacon_putc(*s++);
}

// Distinct prefix so the host-side capture can separate beacon lines from ROM
// output, bootloader log lines and ordinary application logging on one wire.
static inline void offband_beacon_line(const char* s) {
  offband_beacon_puts("[BEACON] ");
  offband_beacon_puts(s);
  offband_beacon_putc('\r');
  offband_beacon_putc('\n');
}

// Block until the TX FIFO has drained. Serial.begin() software-resets the UART
// controller, which FLUSHES the hardware FIFO -- so a beacon line emitted
// immediately before it can be truncated mid-transmission. Call this before any
// known UART reconfiguration. (Gemini review, #740.)
static inline void offband_beacon_flush(void) {
  uint32_t guard = 2000000;   // bounded for the same reason as offband_beacon_putc
  while (guard--) {
    if ((((READ_PERI_REG(UART_STATUS_REG(OFFBAND_BEACON_UART)) >> UART_TXFIFO_CNT_S)
          & UART_TXFIFO_CNT_V)) == 0) break;
  }
}

#define OFFBAND_BEACON(msg) offband_beacon_line(msg)
#define OFFBAND_BEACON_FLUSH() offband_beacon_flush()

// Emitted once, from exactly one translation unit -- the one that defines
// OFFBAND_BEACON_DEFINE_CTOR before including this header (main.cpp). Priority
// 101 is the lowest user-assignable value, so this runs before the variant's
// static objects (board, radio, display, sensors) are constructed.
#if defined(OFFBAND_BEACON_DEFINE_CTOR)
__attribute__((constructor(101)))
static void offband_beacon_ctor(void) {
  offband_beacon_line("APP:CTOR -- earliest static ctor; bootloader + IDF startup COMPLETED");
}
#endif

#else  // !OFFBAND_BOOT_BEACON

// Gemini review (#740): these were empty `static inline` functions. Any
// translation unit that includes this header without calling them emits
// -Wunused-function, which breaks a -Werror build. Macros generate no symbol at
// all, so there is nothing to be unused. This header reaches every companion env
// in the fleet, so the safe form is the required one.
#define OFFBAND_BEACON(msg) ((void)0)
#define OFFBAND_BEACON_FLUSH() ((void)0)
#define offband_beacon_puts(s) ((void)0)
#define offband_beacon_line(s) ((void)0)
#define offband_beacon_flush() ((void)0)

#endif
