#pragma once

// #740 -- boot beacon.
//
// WHY THIS EXISTS
// ---------------
// Three stages of boot are invisible to every ordinary instrument (see #702):
//
//   1. the second-stage bootloader is built with logging compiled out, so it
//      prints nothing on success OR failure;
//   2. prebuilt core libraries compile out their own INFO/DEBUG lines, and they
//      cannot be re-enabled at runtime;
//   3. MeshLog and the CrashLog ring go to `Serial`, which on a native-USB part
//      is generated by the chip itself -- it dies with the chip, so it can never
//      witness a boot that failed.
//
// The beacon writes straight to a UART wire, needing no driver, no RTOS, no
// Arduino core and no logging framework -- so it is usable from the very first
// executable instruction of the application, specifically from a
// constructor(101), which runs ahead of every other C++ static constructor.
//
// The single marker APP:CTOR is the load-bearing one: if it appears after a
// reset, the bootloader and platform startup both completed and the fault is in
// our ctors/setup(); if it does not, the fault is at or before the bootloader's
// jump to the app, and no application-level fix can ever address it.
//
// Enable with -D OFFBAND_BOOT_BEACON. Compiles to nothing otherwise, so the call
// sites are safe to leave in shipping code.
//
// #888: the raw-UART writer this is built on now lives in LogMirrorUart.h and is
// per-platform, so the beacon works anywhere that has a back end. The beacon
// keeps its OWN flag rather than riding OFFBAND_LOG_MIRROR_UART -- a build that
// wants normal logs mirrored to a wire should not start emitting boot beacons it
// never asked for, and vice versa. One back end, two independent consumers.

#include "LogMirrorUart.h"

#if defined(OFFBAND_BOOT_BEACON)

// Distinct prefix so a host-side capture can separate beacon lines from ROM
// output, bootloader logging and ordinary application logging on one wire.
static inline void offband_beacon_line(const char* s) {
  offband_log_mirror_puts("[BEACON] ");
  offband_log_mirror_puts(s);
  offband_log_mirror_putc('\r');
  offband_log_mirror_putc('\n');
}

#define OFFBAND_BEACON(msg)    offband_beacon_line(msg)

// Flush before any known UART reconfiguration. On platforms where the mirror
// shares a controller with something the core may re-initialise, Serial.begin()
// can software-reset that controller and flush bytes still in flight, truncating
// a line mid-transmission. (Gemini review, #740.)
#define OFFBAND_BEACON_FLUSH() offband_log_mirror_flush()

// Emitted once, from exactly one translation unit -- the one that defines
// OFFBAND_BEACON_DEFINE_CTOR before including this header (main.cpp). Priority
// 101 is the lowest user-assignable value, so this runs before the variant's
// static objects (board, radio, display, sensors) are constructed.
#if defined(OFFBAND_BEACON_DEFINE_CTOR)
__attribute__((constructor(101)))
static void offband_beacon_ctor(void) {
  offband_beacon_line("APP:CTOR -- earliest static ctor; bootloader + platform startup COMPLETED");
}
#endif

#else  // beacon disabled

// Macros, not empty inline functions -- an uncalled inline emits
// -Wunused-function and breaks a -Werror build. This header reaches every env in
// the fleet, so the safe form is the required one. (Gemini review, #740.)
#define OFFBAND_BEACON(msg)    ((void)0)
#define OFFBAND_BEACON_FLUSH() ((void)0)
#define offband_beacon_line(s) ((void)0)

#endif  // OFFBAND_BOOT_BEACON
