#include "HeltecRCC6Board.h"

void HeltecRCC6Board::begin() {
  ESP32Board::begin();

#ifdef PIN_VEXT_EN
  // Vext_3V3 is generated by U3 (TLV75733PDBVR) and its EN pin is driven by
  // VEXT_LDO_Ctrl (GPIO11) through R10, a 100K pulldown to ground -- so the rail
  // is OFF at reset and stays off until firmware asserts it. Vext_3V3 reaches the
  // RA62A through ferrite L3 into a 10 uF + 100 nF decoupled node.
  // `[verified: rendered schematic, U1/U3 comparison -- U1 (CE6260B33M -> VDD_3V3)
  //  has EN tied to IN and is unconditional; U3 does not]`
  //
  // `[schematic-derived: #805 -- NOT measured]` THIS RAIL ALMOST CERTAINLY DOES
  // NOT POWER THE RADIO. Vext_3V3's only destination is U5 pin 25, which the
  // RA62A symbol labels NC; the net name appears exactly twice on the whole
  // single-page sheet (the U3 output, and that pin). The module's supply is
  // VDD_3V3 on U5 pin 10, off U1, which is unconditional.
  //
  // Evidence, computed from the PDF's vector geometry rather than read off a
  // render: the sole vertical segment reaching the Vext node is at x=640.63. The
  // PDF carries its own per-pin designators (PIU50nn); matching every bottom-edge
  // pin against the drawn stubs gives agreement within +/-0.61 for every pin that
  // HAS a stub, and x=640.63 lands on PIU5025 (641.00, delta -0.37) with its
  // neighbours 3.59 away. Pins 23 and 30 deviate ~3.3 precisely because no stub
  // is drawn for them -- they are NC with no wire, which is corroboration, not
  // error.
  //
  // WHAT WOULD FALSIFY IT, and why this is not called `[verified:]`: no voltage
  // was ever measured. A schematic read -- however carefully computed -- is not a
  // measurement, and this part is explicitly dual-variant (RA62A_LF/RA62A_HF), so
  // a pin that is NC on one population can be live on the other. The cheap
  // settling test is a multimeter on U5 pin 10 and pin 25 with GPIO11 de-asserted
  // and asserted. Until someone does that, this is a strong inference.
  //
  // SO WHY STILL ASSERT IT? Precisely BECAUSE it is inference and not measurement.
  // If the inference is right, asserting costs the TLV75733's quiescent draw and
  // nothing else. If it is wrong, NOT asserting is a silent dead SX1262 with no
  // obvious pointer at a power rail. That asymmetry favours asserting until the
  // measurement exists -- and removing it is the owner's call regardless, since it
  // changes runtime behaviour on a board already verified working. PIN_VEXT_EN
  // stays defined either way, so one line restores it.
  //
  // NOT resolved by this: SELECT (GPIO7) -- see the note at the end of begin().
  pinMode(PIN_VEXT_EN, OUTPUT);
  digitalWrite(PIN_VEXT_EN, PIN_VEXT_EN_ACTIVE);
  delay(10);   // let the LDO settle before anything downstream is touched
#endif

  // Battery divider is enable-gated: PIN_ADC_CTRL switches the divider feeding
  // PIN_VBAT_READ so it does not bleed the cell continuously. Park it DISABLED
  // here; getBattMilliVolts() owns the enable/sample/disable cycle.
  //
  // POLARITY IS MEASURED, NEVER INHERITED. ADC_CTRL_ENABLED comes from this
  // board's own schematic and n30nex's shipping variant, not from a sibling.
  // Copying this polarity from another board is the #602 failure: on the Wio
  // Tracker L1 Pro an inherited polarity made SafeBoot disable the divider,
  // sample it dead, read below SLEEP_MV and deep-sleep before USB init -- a
  // fully charged board presenting as completely dead.
#ifdef PIN_ADC_CTRL
  pinMode(PIN_ADC_CTRL, OUTPUT);
  digitalWrite(PIN_ADC_CTRL, !ADC_CTRL_ENABLED);
#endif

  // SELECT (GPIO7) is deliberately NOT driven. The module is marked
  // RA62A_LF/RA62A_HF -- a dual LF/HF part -- so SELECT plausibly chooses the RF
  // path, but that is `[hypothesis: untested]` and n30nex does not drive it
  // either. Driving a strap-capable pin whose function is unconfirmed is worse
  // than leaving it at its board default.
  //
  // Tracked on #805 ("Related unknown -- do not lose this one"), NOT #806, which
  // is closed. If SELECT does choose the RF path, the wrong default presents as
  // mediocre range rather than a clean failure -- the failure mode nobody files
  // a bug for. Settle it before this board ships to testers.
}

uint16_t HeltecRCC6Board::getBattMilliVolts() {
#if defined(PIN_ADC_CTRL) && defined(PIN_VBAT_READ)
  analogReadResolution(12);
  analogSetAttenuation(ADC_2_5db);

  digitalWrite(PIN_ADC_CTRL, ADC_CTRL_ENABLED);
  delay(10);                      // divider settle
  uint32_t raw = 0;
  for (int i = 0; i < 8; i++) {
    raw += analogReadMilliVolts(PIN_VBAT_READ);
  }
  raw = raw / 8;
  digitalWrite(PIN_ADC_CTRL, !ADC_CTRL_ENABLED);

  return (uint16_t)(adc_mult * raw);
#else
  return 0;
#endif
}

bool HeltecRCC6Board::setAdcMultiplier(float multiplier) {
  adc_mult = multiplier == 0.0f ? ADC_MULTIPLIER : multiplier;
  return true;
}

const char* HeltecRCC6Board::getManufacturerName() const {
  return "Heltec RCC6";
}
