#include "HeltecRCC6Board.h"

void HeltecRCC6Board::begin() {
  ESP32Board::begin();

#ifdef PIN_VEXT_EN
  // Vext_3V3 is generated by U3 (TLV75733PDBVR) and its EN pin is driven by
  // VEXT_LDO_Ctrl (GPIO11) through R10, a 100K pulldown to ground -- so the rail
  // is OFF at reset and stays off until firmware asserts it. Vext_3V3 reaches the
  // RA62A through ferrite L3 into a 10 uF + 100 nF decoupled node.
  // `[verified: rendered schematic, U1/U3 comparison -- U1 (CE6260B33M -> VDD_3V3)
  //  has EN tied to IN and is unconditional; U3 does not]`
  //
  // `[resolved: #805]` THIS RAIL DOES NOT POWER THE RADIO. Settled from the
  // schematic's vector geometry (not a render): Vext_3V3's only destination is
  // U5 pin 25, which the RA62A symbol labels NC. The net name appears exactly
  // twice on the whole sheet -- the U3 output, and that pin. The module's actual
  // supply is VDD_3V3 on U5 pin 10, off U1, which is unconditional.
  //
  // Confirmed three ways: the sole vertical segment reaching the Vext node is at
  // x=640.63; a stub-to-label offset calibrated on pins 21/22 (SPI_MOSI/SPI_CS,
  // both exactly +1.530) predicts pin 25 at x=640.62 -- delta 0.01 against a 3.59
  // pin pitch; and the PDF's own designator PIU5025 sits at x=641.00 beside the
  // NC label. The 10uF+100nF decoupling that made this look like a supply rail IS
  // one -- it just lands on a pin this population does not connect. Most likely
  // provisioned for the HaLow module on the shared carrier `[hypothesis:]`.
  //
  // SO WHY STILL ASSERT IT? Only because turning it off changes runtime behaviour
  // on a board already verified working, and that is the owner's call, not a
  // side-effect of a documentation fix. It costs the TLV75733's quiescent draw
  // for zero function. Dropping the two lines below is the power-saving move and
  // is safe on this evidence; PIN_VEXT_EN stays defined either way so the rail
  // remains documented and one line brings it back.
  //
  // NOT resolved by this: SELECT (GPIO7) -- see the note at the end of begin().
  pinMode(PIN_VEXT_EN, OUTPUT);
  digitalWrite(PIN_VEXT_EN, PIN_VEXT_EN_ACTIVE);
  delay(10);   // let the LDO settle before anything downstream is touched
#endif

  // Battery divider is enable-gated: PIN_ADC_CTRL switches the divider feeding
  // PIN_VBAT_READ so it does not bleed the cell continuously. Park it DISABLED
  // here; getBattMilliVolts() owns the enable/sample/disable cycle.
  //
  // POLARITY IS MEASURED, NEVER INHERITED. ADC_CTRL_ENABLED comes from this
  // board's own schematic and n30nex's shipping variant, not from a sibling.
  // Copying this polarity from another board is the #602 failure: on the Wio
  // Tracker L1 Pro an inherited polarity made SafeBoot disable the divider,
  // sample it dead, read below SLEEP_MV and deep-sleep before USB init -- a
  // fully charged board presenting as completely dead.
#ifdef PIN_ADC_CTRL
  pinMode(PIN_ADC_CTRL, OUTPUT);
  digitalWrite(PIN_ADC_CTRL, !ADC_CTRL_ENABLED);
#endif

  // SELECT (GPIO7) is deliberately NOT driven. The module is marked
  // RA62A_LF/RA62A_HF -- a dual LF/HF part -- so SELECT plausibly chooses the RF
  // path, but that is `[hypothesis: untested]` and n30nex does not drive it
  // either. Driving a strap-capable pin whose function is unconfirmed is worse
  // than leaving it at its board default.
  //
  // Tracked on #805 ("Related unknown -- do not lose this one"), NOT #806, which
  // is closed. If SELECT does choose the RF path, the wrong default presents as
  // mediocre range rather than a clean failure -- the failure mode nobody files
  // a bug for. Settle it before this board ships to testers.
}

uint16_t HeltecRCC6Board::getBattMilliVolts() {
#if defined(PIN_ADC_CTRL) && defined(PIN_VBAT_READ)
  analogReadResolution(12);
  analogSetAttenuation(ADC_2_5db);

  digitalWrite(PIN_ADC_CTRL, ADC_CTRL_ENABLED);
  delay(10);                      // divider settle
  uint32_t raw = 0;
  for (int i = 0; i < 8; i++) {
    raw += analogReadMilliVolts(PIN_VBAT_READ);
  }
  raw = raw / 8;
  digitalWrite(PIN_ADC_CTRL, !ADC_CTRL_ENABLED);

  return (uint16_t)(adc_mult * raw);
#else
  return 0;
#endif
}

bool HeltecRCC6Board::setAdcMultiplier(float multiplier) {
  adc_mult = multiplier == 0.0f ? ADC_MULTIPLIER : multiplier;
  return true;
}

const char* HeltecRCC6Board::getManufacturerName() const {
  return "Heltec RCC6";
}
