#include "HeltecRCC6Board.h"

void HeltecRCC6Board::begin() {
  ESP32Board::begin();

#ifdef PIN_VEXT_EN
  // Vext_3V3 is generated by U3 (TLV75733PDBVR) and its EN pin is driven by
  // VEXT_LDO_Ctrl (GPIO11) through R10, a 100K pulldown to ground -- so the rail
  // is OFF at reset and stays off until firmware asserts it. Vext_3V3 reaches the
  // RA62A through ferrite L3 into a 10 uF + 100 nF decoupled node.
  // `[verified: rendered schematic, U1/U3 comparison -- U1 (CE6260B33M -> VDD_3V3)
  //  has EN tied to IN and is unconditional; U3 does not]`
  //
  // WHY WE ASSERT IT. Whether this rail gates the radio, the display, or both is
  // NOT yet established (#805) -- the module pin it lands on was occluded in the
  // render and has not been confirmed. Asserting it is the safe direction: if it
  // feeds the radio, leaving it low is a silent dead SX1262 with no obvious
  // pointer at a power rail; if it feeds only the display, asserting it costs a
  // few mA. No reference implementation drives this pin -- n30nex's variant never
  // touches GPIO11 -- so there is nothing to inherit here.
  //
  // Revisit under #805, and if the rail turns out to be display-only, gate it
  // with the display rather than holding it up unconditionally.
  pinMode(PIN_VEXT_EN, OUTPUT);
  digitalWrite(PIN_VEXT_EN, PIN_VEXT_EN_ACTIVE);
  delay(10);   // let the LDO settle before anything downstream is touched
#endif

  // Battery divider is enable-gated: PIN_ADC_CTRL switches the divider feeding
  // PIN_VBAT_READ so it does not bleed the cell continuously. Park it DISABLED
  // here; getBattMilliVolts() owns the enable/sample/disable cycle.
  //
  // POLARITY IS MEASURED, NEVER INHERITED. ADC_CTRL_ENABLED comes from this
  // board's own schematic and n30nex's shipping variant, not from a sibling.
  // Copying this polarity from another board is the #602 failure: on the Wio
  // Tracker L1 Pro an inherited polarity made SafeBoot disable the divider,
  // sample it dead, read below SLEEP_MV and deep-sleep before USB init -- a
  // fully charged board presenting as completely dead.
#ifdef PIN_ADC_CTRL
  pinMode(PIN_ADC_CTRL, OUTPUT);
  digitalWrite(PIN_ADC_CTRL, !ADC_CTRL_ENABLED);
#endif

  // SELECT (GPIO7) is deliberately NOT driven. The module is marked
  // RA62A_LF/RA62A_HF -- a dual LF/HF part -- so SELECT plausibly chooses the RF
  // path, but that is `[hypothesis: untested]` and n30nex does not drive it
  // either. Driving a strap-capable pin whose function is unconfirmed is worse
  // than leaving it at its board default. Tracked on #806.
}

uint16_t HeltecRCC6Board::getBattMilliVolts() {
#if defined(PIN_ADC_CTRL) && defined(PIN_VBAT_READ)
  analogReadResolution(12);
  analogSetAttenuation(ADC_2_5db);

  digitalWrite(PIN_ADC_CTRL, ADC_CTRL_ENABLED);
  delay(10);                      // divider settle
  uint32_t raw = 0;
  for (int i = 0; i < 8; i++) {
    raw += analogReadMilliVolts(PIN_VBAT_READ);
  }
  raw = raw / 8;
  digitalWrite(PIN_ADC_CTRL, !ADC_CTRL_ENABLED);

  return (uint16_t)(adc_mult * raw);
#else
  return 0;
#endif
}

bool HeltecRCC6Board::setAdcMultiplier(float multiplier) {
  adc_mult = multiplier == 0.0f ? ADC_MULTIPLIER : multiplier;
  return true;
}

const char* HeltecRCC6Board::getManufacturerName() const {
  return "Heltec RCC6";
}
