#!/usr/bin/env python3
"""Generate a 4bpp antialiased JetBrains Mono glyph table for the RC32 panel (#758).

WHY THIS EXISTS
    The RC32 draws text with `font5x7`, a 5x7 bitmap whose every pixel `drawChar()`
    scales into a rectangle -- 1 wide x 2 tall at size 1. So a character occupies
    5x14 physical pixels while carrying only 7 rows of real information. It is not
    blocky because it is small; it is blocky because it is STRETCHED.

    This emits real glyphs with per-pixel coverage instead, which the driver blends
    against the background. Blending needs to read the destination, which only
    became cheap when #747 gave the driver a readable back buffer -- so this is a
    direct dividend of that work and could not have been done before it landed.

WHY 4 BITS
    16 coverage levels is past the point where edges read as smooth at this size,
    and it halves the table against 8bpp. The table is `95 * cell_w * cell_h / 2`
    bytes -- see --size below.

FONT + LICENCE
    JetBrains Mono, SIL Open Font License 1.1 -- embedding is permitted, and it is
    the face the Offband wordmark itself is set in, so splash text matches the logo
    directly above it. The TTF is NOT committed; the generated header is. Pass the
    extracted TTF with --ttf.

    Copyright 2020 The JetBrains Mono Project Authors
    https://github.com/JetBrains/JetBrainsMono

SIZE CHOICE
    JetBrains Mono's advance is exactly 6.0 px at 10 px, with a 14 px line box --
    which is precisely what font5x7-at-1x2 already occupies. At size 10 this is a
    DROP-IN: `getTextWidth()` is unchanged and nothing in the UI relayouts. Larger
    sizes look better but widen the advance (8 px at 13 px), which changes every
    centring and ellipsis decision on the board. Default is the safe one.

Usage:
    python scripts/gen-jbm-font.py --ttf <JetBrainsMono-Regular.ttf> [--size 10]
"""
from __future__ import annotations
import argparse
from dataclasses import dataclass
from pathlib import Path

# Pillow is needed only to RASTERISE. The pure arithmetic below (packing,
# quantisation, compositing, placement) has no image dependency, and the
# self-tests exercise it without Pillow present -- so import defensively
# rather than making the whole module unimportable on a host without it.
try:
    from PIL import Image, ImageDraw, ImageFont
    HAVE_PIL = True
except ImportError:  # pragma: no cover - exercised by CI hosts without Pillow
    HAVE_PIL = False

FIRST_CH, LAST_CH = 32, 126   # printable ASCII


def quantise4(v: int) -> int:
    """8-bit coverage -> 4-bit. Rounds, so 255 reaches 15 and mid-tones survive."""
    return (v * 15 + 127) // 255


def pack_nibbles(values) -> bytes:
    """Two 4-bit pixels per byte, first pixel in the HIGH nibble.

    An odd count is padded with a blank, so a glyph's byte length is always
    ceil(px / 2) and the decoder can index without a special case.
    """
    out = bytearray()
    it = list(values)
    if len(it) % 2:
        it.append(0)
    for i in range(0, len(it), 2):
        out.append(((it[i] & 0xF) << 4) | (it[i + 1] & 0xF))
    return bytes(out)


def _metrics(ttf: str, size: int):
    f = ImageFont.truetype(ttf, size)
    ascent, descent = f.getmetrics()
    advance = int(round(f.getlength("M")))
    return f, advance, ascent, descent


def render_glyph(ttf: str, ch: str, size: int):
    """Coverage values (0..15) for one glyph, row-major, cell_w * cell_h long."""
    f, advance, ascent, descent = _metrics(ttf, size)
    cell_w, cell_h = advance, ascent + descent
    img = Image.new("L", (cell_w, cell_h), 0)
    # Draw from the cell origin with the font's own ascent as the baseline, so
    # every glyph shares one baseline and the grid stays monospace.
    ImageDraw.Draw(img).text((0, 0), ch, font=f, fill=255)
    return [quantise4(p) for p in img.getdata()]


@dataclass
class GlyphTable:
    advance: int
    cell_w: int
    cell_h: int
    ascent: int
    glyphs: list


def glyph_table(ttf: str, size: int) -> GlyphTable:
    f, advance, ascent, descent = _metrics(ttf, size)
    glyphs = [render_glyph(ttf, chr(c), size) for c in range(FIRST_CH, LAST_CH + 1)]
    return GlyphTable(advance=advance, cell_w=advance, cell_h=ascent + descent,
                      ascent=ascent, glyphs=glyphs)


def emit_header(tbl: GlyphTable, ttf_name: str, size: int) -> str:
    packed = b"".join(pack_nibbles(g) for g in tbl.glyphs)
    per_glyph = (tbl.cell_w * tbl.cell_h + 1) // 2
    rows = []
    for i in range(0, len(packed), 16):
        rows.append("  " + ", ".join(f"0x{b:02x}" for b in packed[i:i + 16]) + ",")
    body = "\n".join(rows)
    return f"""// JbmFont.h -- antialiased JetBrains Mono glyph table for the RC32 panel (#758).
// GENERATED by scripts/gen-jbm-font.py from {ttf_name} at {size}px.
// Do not hand-edit; regenerate.
//
// FONT LICENCE -- JetBrains Mono is licensed under the SIL Open Font License 1.1.
//   Copyright 2020 The JetBrains Mono Project Authors
//   https://github.com/JetBrains/JetBrainsMono
// This header contains glyph coverage data derived from that font. The OFL notice
// travels with it; do not strip this block.
//
// FORMAT
//   4 bits of coverage per pixel, two pixels per byte, FIRST pixel in the HIGH
//   nibble. Row-major within a glyph, {tbl.cell_w}x{tbl.cell_h} px per cell,
//   {per_glyph} bytes per glyph, printable ASCII {FIRST_CH}..{LAST_CH} in order.
//   Coverage is blended against the background by the driver -- it is NOT a
//   1-bit mask, and thresholding it would defeat the entire point.
#pragma once

#include <stdint.h>

#define JBM_FIRST_CH   {FIRST_CH}
#define JBM_LAST_CH    {LAST_CH}
#define JBM_CELL_W     {tbl.cell_w}
#define JBM_CELL_H     {tbl.cell_h}
#define JBM_ADVANCE    {tbl.advance}
#define JBM_ASCENT     {tbl.ascent}
#define JBM_BYTES_PER_GLYPH {per_glyph}

static const uint8_t jbm_glyphs[] = {{
{body}
}};
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ttf", required=True, help="JetBrainsMono-Regular.ttf (not committed)")
    ap.add_argument("--size", type=int, default=10,
                    help="px size; 10 keeps font5x7's 6px advance and 14px line box")
    ap.add_argument("--out", default=str(
        Path(__file__).resolve().parent.parent / "src/helpers/ui/JbmFont.h"))
    a = ap.parse_args()

    tbl = glyph_table(a.ttf, a.size)
    Path(a.out).write_text(emit_header(tbl, Path(a.ttf).name, a.size))
    total = len(tbl.glyphs) * ((tbl.cell_w * tbl.cell_h + 1) // 2)
    print(f"wrote {a.out}")
    print(f"  {len(tbl.glyphs)} glyphs, {tbl.cell_w}x{tbl.cell_h} cell, "
          f"advance {tbl.advance}, {total:,} B")


if __name__ == "__main__":
    main()
