#!/usr/bin/env python3
"""Generate offband_logo.h -- 1-bit Offband brand splash bitmaps (#153).

The OLED splash renders the Offband brand lockup (radar mark + "offband"
wordmark). 1-bit display logos must be produced at native size, not shrunk
from a large raster (an 8:1 downscale smears sub-pixel detail). So:

  * wordmark -- cropped from the brand lockup PNG's alpha channel (the real
    JetBrains Mono wordmark), then resized to target width.
  * mark     -- rendered from the lockup SVG's vector geometry (two concentric
    arcs r=12/r=19 about centre (28,38), centre dot, corner blip), supersampled.

Output is MSB-first byte arrays for Adafruit_GFX drawBitmap (SSD1306Display).
The morse underline in the brand lockup is intentionally omitted -- its dots are
sub-pixel at OLED size and only ever read as a smear.

Usage:
    python scripts/gen-offband-logo.py [--src <lockup.png>] [--out <header>]

--src defaults to the offband-site brand asset (per-host path); regenerate after
any brand-mark change. Output header is committed so a build needs no PIL.
"""
from __future__ import annotations
import argparse
from pathlib import Path

from PIL import Image, ImageDraw

# Sizes tuned for the 128x64 OLED lockup (mark + 4px gap + wordmark = 119px).
MARK_TARGET_H = 30
WORD_TARGET_W = 86
WORD_THRESHOLD = 120
MARK_THRESHOLD = 110


def _bits_msb(mask):
    """Pack an L-mode mask to MSB-first bytes (Adafruit drawBitmap order)."""
    w, h = mask.size
    px = mask.load()
    row_bytes = (w + 7) // 8
    data = bytearray(row_bytes * h)
    thr = mask.info.get("thr", 128)
    for y in range(h):
        for x in range(w):
            if px[x, y] >= thr:
                data[y * row_bytes + (x >> 3)] |= (0x80 >> (x & 7))
    return data, row_bytes, w, h


def wordmark(png_path: str, target_w: int):
    im = Image.open(png_path).convert("RGBA")
    # Crop right of the mark and above the morse underline, then trim to ink.
    # NOTE: these bounds are coupled to the current logo-lockup-light.png layout
    # (1000x256). If the brand asset is resized/reflowed, re-validate them -- a bad
    # crop yields a garbled wordmark, which the on-device splash check would catch.
    w = im.crop((250, 0, 1000, 186))
    w = w.crop(w.split()[3].getbbox())
    alpha = w.split()[3]
    w0, h0 = w.size
    th = round(target_w * h0 / w0)
    m = alpha.resize((target_w, th), Image.LANCZOS)
    m.info["thr"] = WORD_THRESHOLD
    return _bits_msb(m)


def mark(target_h: int, supersample: int = 14):
    # Work in the SVG mark-group coordinate space (centre dot at (28,38)).
    minx, miny, maxx, maxy = 8, 14, 50, 58
    bw, bh = maxx - minx, maxy - miny
    sc = (target_h * supersample) / bh
    cw, ch = round(bw * sc), round(bh * sc)
    img = Image.new("L", (cw, ch), 0)
    dr = ImageDraw.Draw(img)
    X = lambda x: (x - minx) * sc
    Y = lambda y: (y - miny) * sc
    stroke = max(2, round(2.4 * sc))

    def arc(r, start, end):
        dr.arc([X(28 - r), Y(38 - r), X(28 + r), Y(38 + r)], start, end,
               fill=255, width=stroke)

    # ~280deg concentric arcs (gap toward lower-right), per the brand mark.
    arc(19, 10, 290)
    arc(12, 10, 290)

    def dot(cx, cy, r):
        dr.ellipse([X(cx) - r * sc, Y(cy) - r * sc, X(cx) + r * sc, Y(cy) + r * sc],
                   fill=255)

    dot(28, 38, 3.6)      # centre
    dot(46.1, 17.9, 3.0)  # corner blip
    small = img.resize((round(cw / supersample), round(ch / supersample)), Image.LANCZOS)
    small.info["thr"] = MARK_THRESHOLD
    return _bits_msb(small)


def carray(name: str, data: bytearray, row_bytes: int) -> str:
    out = [f"static const uint8_t {name}[] = {{"]
    for i in range(0, len(data), row_bytes):
        out.append("  " + ", ".join(f"0x{b:02x}" for b in data[i:i + row_bytes]) + ",")
    out.append("};")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    # Default: the offband-site repo checked out as a sibling of this one
    # (../offband-site). Override with --src if it lives elsewhere.
    default_src = (Path(__file__).resolve().parent.parent.parent /
                   "offband-site/static/img/logo-lockup-light.png")
    ap.add_argument("--src", default=str(default_src))
    ap.add_argument("--out", default=str(
        Path(__file__).resolve().parent.parent /
        "examples/companion_radio/ui-new/offband_logo.h"))
    a = ap.parse_args()

    md, mrb, mw, mh = mark(MARK_TARGET_H)
    wd, wrb, ww, wh = wordmark(a.src, WORD_TARGET_W)

    header = f"""// offband_logo.h -- Offband brand splash bitmaps for the OLED splash (#153).
// GENERATED by scripts/gen-offband-logo.py from the brand lockup
//   ({Path(a.src).name}). Wordmark cropped from the PNG alpha mask; mark
//   rendered from the lockup's vector geometry (two arcs + two dots). The morse
//   underline is omitted (sub-pixel at this size). 1-bit, MSB-first
//   (Adafruit_GFX drawBitmap / SSD1306Display). Do not hand-edit; regenerate.
#pragma once
#ifdef OFFBAND_VERSION

#define OFFBAND_MARK_W {mw}
#define OFFBAND_MARK_H {mh}
{carray('offband_mark', md, mrb)}

#define OFFBAND_WORD_W {ww}
#define OFFBAND_WORD_H {wh}
{carray('offband_word', wd, wrb)}

#endif // OFFBAND_VERSION
"""
    Path(a.out).write_text(header)
    print(f"wrote {a.out}\n  mark {mw}x{mh} ({len(md)}B), word {ww}x{wh} ({len(wd)}B)")


if __name__ == "__main__":
    main()
