#!/usr/bin/env python3
"""Generate variants/qcc_badge/QccSplashArt.h from the QCC 0x4 eye (#1172).

Source: variants/qcc_badge/art/qcc_eye_50x50.xbm, a standard XBM (LSB-first rows).
Output: the same pixels MSB-first, the order DisplayDriver::drawXbm expects on the
OLED drivers (Adafruit_GFX drawBitmap). Do not hand-edit the header; regenerate.

Usage:
  python scripts/gen-qcc-splash.py            # print the header to stdout
  python scripts/gen-qcc-splash.py --src PATH
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = ROOT / "variants" / "qcc_badge" / "art" / "qcc_eye_50x50.xbm"


def parse_xbm(text):
    # An XBM names everything after its image: <name>_bits[], <name>_width, <name>_height.
    arr = re.search(r"(\w+)_bits\s*\[\s*\][^=]*=\s*\{([^}]*)\}", text)
    if not arr:
        raise ValueError("no <name>_bits[] = { ... } array")
    name = re.escape(arr.group(1))
    w = re.search(r"^\s*#define\s+%s_width\s+(\d+)" % name, text, re.M)
    h = re.search(r"^\s*#define\s+%s_height\s+(\d+)" % name, text, re.M)
    if not (w and h):
        raise ValueError(f"no #define {arr.group(1)}_width / _height")
    w, h = int(w.group(1)), int(h.group(1))
    data = [int(t, 16) for t in re.findall(r"0x[0-9A-Fa-f]{1,2}", arr.group(2))]
    row_bytes = (w + 7) // 8
    if len(data) != row_bytes * h:
        raise ValueError(f"expected {row_bytes * h} bytes for {w}x{h}, got {len(data)}")
    return w, h, data


def reverse_bits(b):
    return int(f"{b:08b}"[::-1], 2)


def to_msb_first(data):
    return [reverse_bits(b) for b in data]


def render_header(w, h, data):
    row_bytes = (w + 7) // 8
    out = [
        "// QccSplashArt.h -- the QCC 0x4 eye for the badge splash (#1172).",
        "// GENERATED by scripts/gen-qcc-splash.py from variants/qcc_badge/art/qcc_eye_50x50.xbm.",
        "// 1-bit, MSB-first (Adafruit_GFX drawBitmap / DisplayDriver::drawXbm). Do not hand-edit; regenerate.",
        "// Static data: include it from one .cpp only (QccSplash.cpp), as with OffbandLogo.h.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"#define QCC_EYE_W {w}",
        f"#define QCC_EYE_H {h}",
        "",
        "static const uint8_t qcc_eye[] = {",
    ]
    for r in range(h):
        row = data[r * row_bytes:(r + 1) * row_bytes]
        out.append("  " + ", ".join(f"0x{b:02X}" for b in row) + ",")
    out.append("};")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--src", default=str(DEFAULT_SRC))
    args = ap.parse_args()
    w, h, data = parse_xbm(Path(args.src).read_text())
    sys.stdout.write(render_header(w, h, to_msb_first(data)))


if __name__ == "__main__":
    main()
