#!/usr/bin/env python3
"""Generate src/helpers/ui/BadgeFonts.h from the Adafruit GFX font headers (#1237).

The badge's layout measures text in pixels, because Org_01 is proportional. It has to
measure exactly what the display draws, so the advance widths come from the same headers
the firmware compiles rather than from a hand-written table.

    python tools/gen_badge_fonts.py [path-to-Adafruit-GFX-Library]

The default path is the badge env's library copy under .pio. Re-run it if the library
version changes; the header records which version it came from.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

DEFAULT_LIB = Path(".pio/libdeps/QCC_Badge_companion_radio_ble/Adafruit GFX Library")
OUT = Path("src/helpers/ui/BadgeFonts.h")
FIRST, LAST = 0x20, 0x7E


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def font_advances(lib: Path, name: str) -> tuple[list[int], int]:
    """(advance per character from 0x20 to 0x7E, row pitch) for a GFX font."""
    src = (lib / "Fonts" / f"{name}.h").read_text(errors="ignore")
    # The badge build doesn't define TOMTHUMB_USE_EXTENDED, so those tables aren't compiled.
    src = re.sub(r"#if \(TOMTHUMB_USE_EXTENDED\).*?#endif", "", src, flags=re.S)
    start = src.index("{", src.index("Glyphs[]"))
    glyphs = re.findall(r"\{\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(-?\d+),\s*(-?\d+)\s*\}",
                        strip_comments(src[start:src.index("};", start)]))
    tail = src[src.rindex("const GFXfont"):]
    first, last, yadv = (int(x, 0) for x in
                         re.findall(r"(0x[0-9A-Fa-f]+|\d+)\s*,\s*(0x[0-9A-Fa-f]+|\d+)\s*,\s*(\d+)\s*\}", tail)[0])
    if (first, last) != (FIRST, LAST):
        raise SystemExit(f"{name}: covers {first:#x}..{last:#x}, expected {FIRST:#x}..{LAST:#x}")
    if len(glyphs) != LAST - FIRST + 1:
        raise SystemExit(f"{name}: {len(glyphs)} glyphs, expected {LAST - FIRST + 1}")
    return [int(g[3]) for g in glyphs], yadv


def version(lib: Path) -> str:
    for line in (lib / "library.properties").read_text(errors="ignore").splitlines():
        if line.startswith("version="):
            return line.split("=", 1)[1].strip()
    return "unknown"


def table(name: str, advances: list[int]) -> str:
    rows = []
    for i in range(0, len(advances), 16):
        rows.append("    " + " ".join(f"{a}," for a in advances[i:i + 16]))
    # static, not an inline variable: the nRF52 build pins no -std, so stay in C++11.
    return f"static const uint8_t {name}[] = {{\n" + "\n".join(rows) + "\n};\n"


def main() -> None:
    lib = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_LIB
    if not (lib / "Fonts").is_dir():
        raise SystemExit(f"no Adafruit GFX library at {lib}")
    org, org_row = font_advances(lib, "Org_01")
    tom, tom_row = font_advances(lib, "TomThumb")
    header = f"""#pragma once

// #1237: what each face's characters measure, so the badge's layout can place text it
// doesn't draw itself. Org_01 is proportional (2-6 px), so counting characters stopped
// being enough.
//
// GENERATED by tools/gen_badge_fonts.py from Adafruit GFX Library {version(lib)} -- the
// same headers the badge build compiles. Don't edit by hand; re-run the generator.
//
// Pure: no Arduino and no mesh.

#include <stddef.h>
#include <stdint.h>

namespace badgeui {{

constexpr uint8_t kFaceFirst = {FIRST:#04x};   // the faces cover {FIRST:#04x}..{LAST:#04x}
constexpr uint8_t kFaceLast = {LAST:#04x};

{table("kBodyAdvance", org)}
{table("kMetaAdvance", tom)}
// A text face: how wide its characters are, how tall its rows sit, and the id the
// display driver takes to select it.
struct Face {{
  const uint8_t* advance;   // per character from kFaceFirst; null for a fixed 6 px face
  uint8_t missing;          // for anything outside the range, and for a fixed face
  uint8_t row_px;           // the pitch rows sit on
  uint8_t id;               // DisplayDriver::setFace
}};

// The display's own 6 x 8 font: every character 6 px, rows 8 px.
inline const Face& fixedFace() {{
  static const Face f = {{nullptr, 6, 8, 0}};
  return f;
}}

// Org_01: the badge's body text. Rows sit {org_row} px apart, so a screen holds 9.
inline const Face& bodyFace() {{
  static const Face f = {{kBodyAdvance, 6, {org_row}, 1}};
  return f;
}}

// TomThumb: status lines, a message's detail line and footers. A 4 x 6 grid, 32 wide.
inline const Face& metaFace() {{
  static const Face f = {{kMetaAdvance, 4, {tom_row}, 2}};
  return f;
}}

inline int charPx(const Face& f, char c) {{
  const uint8_t u = (uint8_t)c;
  if (f.advance == nullptr || u < kFaceFirst || u > kFaceLast) return f.missing;
  return f.advance[u - kFaceFirst];
}}

inline int textPx(const Face& f, const char* s) {{
  int px = 0;
  for (; *s != 0; s++) px += charPx(f, *s);
  return px;
}}

// How many characters of `s` fit in `px`, never splitting past what fits.
inline int fitPx(const Face& f, const char* s, int px) {{
  int used = 0, n = 0;
  for (; s[n] != 0; n++) {{
    const int w = charPx(f, s[n]);
    if (used + w > px) break;
    used += w;
  }}
  return n;
}}

}}  // namespace badgeui
"""
    OUT.write_text(header, encoding="utf-8")
    print(f"wrote {OUT}: body {org_row} px rows, meta {tom_row} px rows, "
          f"from Adafruit GFX {version(lib)}")


if __name__ == "__main__":
    main()
